[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

Lomaps BITS is an innovative maps project that has been brought to life by Happy SW, a software development company hired by Brussels. Where you can add markers, review them and watch the marker of your friends. Not only that but to encourage the activity among the young people BITS has a level system that will give you points for every marker you add.

=== Dedicatory
I wanted to thank Patri and Pablo from lomap_en2a that have helped me with all the doubts I've had along the time, as long as allowing me to use some parts of their code for the solid logic.

=== Requirements Overview
This web application allows filtering of markers by category. It uses the SOLID techniques to have further control surrounding user privacy. Storing the data in pods in full control of the client, allowing even choosing the permissions lomap has.

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

|===
| Goal | Description

| Security | Pods ensure the security of the data, since the control is completely given to the user.

| Performance | The application is able to give reasonable response times when users are interacting with it. Minimizing the overload time as it's decentralized and serverless.

| Availability | The data is both, private and controlled but easily accesed by the allowed users.

| Usability | The application is easy and intuitive.

| Portability | The application is able to run in any device with a browser and internet connection.

| Testability | Tests are done to ensure the quality of the application.

|===
=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role|Description|Expectations
| Council of Brussels | The inventor of the idea | An web application. Which is able to be used by the citizens of Brussels encouraging their daily activity.
| HappySw | The developer team | A web application full filling the desires of Brussels.
| Developers | The software developers | In hands of a Software Architect will create a good documentation and a readable and low coupled code.
| Users | Use the app | An application which they hav econtrol over their data and allow them to have places by their own.
|===