[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

[options="header", cols="1,1"]
|===
| Constraint | Explanation

|SOLID | SOLID is used to decentralice the app and ensure the privacy of the user
| Github | Github is a version control, known to help developers keep track of the changes among a group of developers.

| Deployment in gh pages | The application will be deployed in github pages to ensure it remains up even in long term, not needing a dedicated server.

| Test coverage | Code must meet a decent coverage to ensure a minimum capacity.


|===