[[section-solution-strategy]]
== Solution Strategy


=== Technologies

* *Google Maps API*. Google Maps is probably the most famous tool for online maps. Its api is really intuitive and easy to use. Therefore is a safe way to go
* *Solid Way*. In order to keep the data decentralized solid is chosen. Achieves privacy really easily. It is still expanding so the performance will drop a little bit but it is worth it.
* *React*. React is a really powerful tool to create user interfaces. It is really easy to use and it is really fast. It is also really easy to integrate with the base languages we are using (HTML, CSS and TS).


=== Design
* *Serverless app*. The SOLID initiative give us a semi serverless approach as we don't need an api, but we rely on the solid server to store the data.
* *Client-side component*. The code is in the browser, giving the client the 100% of the code.



[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
