[[section-runtime-view]]
== Runtime View
=== Login to Solid

When the user enters the application, the login page is loaded.

[plantuml,"Login to Solid",png]
----
@startuml
header LoMap-BITS

title Login to Solid

database PodProvider

User -> Application: select pod provider
User -> Application: click login button
Application-> PodProvider: redirect login
User -> PodProvider: login to solid
Application -> PodProvider: useSession()


@enduml
----

=== Add location to the user's map

To add a location, the user clicks on the map. The map will display a marker with a form to add the location. The user fills the form and clicks on the add button.

[plantuml,"Addition of a location",png]
----
@startuml

headerLoMap-BITS

title Addition of a location

database PodProvider

User -> Application: clicks the map
Application -> Application: MarkerForm rendered
User -> MarkerForm: write fields of the location
User -> MarkerForm: click add location
MarkerForm -> MarkerForm: adds location to the map
MarkerForm -> PodProvider: reload the existing markers

@enduml
----

=== Remove location from user's map

To delete a location, the user clicks on an existing marker made by him. The marker will display the info. And at the beggining there's a delete button

[plantuml,"Remove location from map",png]
-----
@startuml

header LoMap-BITS

title Remove a location

database PodProvider
actor User

User -> Map : click on the marker
Map -> Application: Shows the info of the marker
User -> MarkerInfo: click delete button
MarkerInfo -> PodProvider: Delete the location
MarkerInfo -> PodProvider: reload the existing markers
MarkerInfo -> Map: display updated markers

@enduml
-----


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****


